jobs:
- template: common-pipelines.yml
  parameters:
    name: macOS
    vmImage: macOS-10.13

- template: common-pipelines.yml
  parameters:
    name: Linux
    vmImage: ubuntu-16.04

- template: common-pipelines.yml
  parameters:
    name: Windows
    vmImage: vs2017-win2016